# coding: utf-8

"""
    TAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inventory import Inventory  # noqa: E501
from swagger_client.rest import ApiException


class TestInventory(unittest.TestCase):
    """Inventory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInventory(self):
        """Test Inventory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inventory.Inventory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
