# coding: utf-8

"""
    TAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.part_is_vehicle_specific import PartIsVehicleSpecific  # noqa: E501
from swagger_client.rest import ApiException


class TestPartIsVehicleSpecific(unittest.TestCase):
    """PartIsVehicleSpecific unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartIsVehicleSpecific(self):
        """Test PartIsVehicleSpecific"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.part_is_vehicle_specific.PartIsVehicleSpecific()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
